name: "build-and-cache"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, develop, nixify ]
  pull_request: 
    branches: [ main ]

jobs:
  build-and-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-open-dev

      - name: Install and test
        run: |
          nix develop --no-update-lock-file --accept-flake-config --command bash -c "npm i && npm t && npm run build -w ui"

      - name: Build debug zomes
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_TOKEN_HOLOCHAIN_OPEN_DEV }}"
        run: |
          cachix watch-exec holochain-open-dev -- nix build --no-update-lock-file --accept-flake-config -L .#profiles_integrity
          cachix push holochain-open-dev $(nix path-info --json --accept-flake-config --no-warn-dirty .#profiles_integrity | nix run nixpkgs#jq -- -r 'keys[0]')

          cachix watch-exec holochain-open-dev -- nix build --no-update-lock-file --accept-flake-config -L .#profiles
          cachix push holochain-open-dev $(nix path-info --json --accept-flake-config --no-warn-dirty .#profiles | nix run nixpkgs#jq -- -r 'keys[0]')

      - name: Pin debug zomes
        if: github.event_name != 'pull_request'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_TOKEN_HOLOCHAIN_OPEN_DEV }}"
        run: |
          cachix pin holochain-open-dev profiles_integrity_debug $(nix path-info --json --accept-flake-config --no-warn-dirty .#profiles_integrity | nix run nixpkgs#jq -- -r 'keys[0]')

          cachix pin holochain-open-dev profiles_debug $(nix path-info --json --accept-flake-config --no-warn-dirty .#profiles | nix run nixpkgs#jq -- -r 'keys[0]')

      - name: Build release zomes
        if: matrix.os == 'ubuntu-latest'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_TOKEN_HOLOCHAIN_OPEN_DEV }}"
        run: |
          cachix watch-exec holochain-open-dev -- nix build --no-update-lock-file --accept-flake-config -L .#profiles_integrity.meta.release
          cachix push holochain-open-dev $(nix path-info --json --accept-flake-config --no-warn-dirty .#profiles_integrity.meta.release | nix run nixpkgs#jq -- -r 'keys[0]')

          cachix watch-exec holochain-open-dev -- nix build --no-update-lock-file --accept-flake-config -L .#profiles.meta.release
          cachix push holochain-open-dev $(nix path-info --json --accept-flake-config --no-warn-dirty .#profiles.meta.release | nix run nixpkgs#jq -- -r 'keys[0]')

      - name: Pin release zomes
        if: matrix.os == 'ubuntu-latest' && github.event_name != 'pull_request'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_TOKEN_HOLOCHAIN_OPEN_DEV }}"
        run: |
          cachix pin holochain-open-dev profiles_integrity $(nix path-info --json --accept-flake-config --no-warn-dirty .#profiles_integrity.meta.release | nix run nixpkgs#jq -- -r 'keys[0]')

          cachix pin holochain-open-dev profiles $(nix path-info --json --accept-flake-config --no-warn-dirty .#profiles.meta.release | nix run nixpkgs#jq -- -r 'keys[0]')
