name: "main"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extend space
        uses: ./.github/actions/extend-space

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - name: Install and test
        run: |
          nix develop --command bash -c "npm i && npm t && npm run build -w ui"

      - name: Build zomes
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_TOKEN_HOLOCHAIN_OPEN_DEV }}"
        run: |
          cachix watch-exec holochain-open-dev -- nix build -L .#profiles_integrity.meta.debug
          cachix watch-exec holochain-open-dev -- nix build -L .#profiles_integrity
          cachix pin holochain-open-dev profiles_integrity $(nix path-info .#profiles_integrity)

          cachix watch-exec holochain-open-dev -- nix build -L .#profiles.meta.debug
          cachix watch-exec holochain-open-dev -- nix build -L .#profiles
          cachix pin holochain-open-dev profiles $(nix path-info .#profiles)
