name: "test"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, main-0.4, develop ]
  pull_request:
    branches: [ main, main-0.4, develop ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extend space
        uses: ./.github/actions/extend-space

      - name: Install nix
        uses: cachix/install-nix-action@v30

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Install and test
        run: |
          nix develop --command bash -c "npm i && npm t"

