
name: "test-prs"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches: [ main, develop ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extend space
        uses: ./.github/actions/extend-space

        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-24.05

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-open-dev

      - name: Install and test
        run: |
          nix develop --no-update-lock-file --command bash -c "npm i && npm t && npm run build -w ui"
